Models/Discipline.cs
using System.Collections.Generic;

namespace KPI_Schedule.Models
{
    public class Discipline
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public List<Schedule> Schedules { get; set; }
    }
}

Controllers/DisciplineController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using KPI_Schedule.Models;

namespace KPI_Schedule.Controllers
{
    public class DisciplineController : Controller
    {
        public DbSchedule Context { get; }
        public DisciplineController(DbSchedule context) => Context = context;

        public async Task<IActionResult> List()
        {
            return View(await Context.Disciplines.ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Discipline discipline)
        {
            if (ModelState.IsValid)
            {
                Context.Add(discipline);
                await Context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }

            return View(discipline);
        }

        public async Task<IActionResult> Choose(int? id)
        {
            if (id == null)
                return NotFound();

            var element = await Context.Disciplines.FirstOrDefaultAsync(e => e.Id == id);

            if (element == null)
                return NotFound();

            return View(element);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var element = await Context.Disciplines.FirstOrDefaultAsync(e => e.Id == id);

            if (element == null)
                return NotFound();

            return View(element);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Discipline discipline)
        {
            if (ModelState.IsValid)
            {
                Context.Update(discipline);
                await Context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }

            return View(discipline);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var element = await Context.Disciplines.FirstOrDefaultAsync(e => e.Id == id);

            if (element == null)
                return NotFound();

            return View(element);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            Context.Disciplines.Remove(await Context.Disciplines.FindAsync(id));
            await Context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }
    }
}

Views/Discipline/Choose.cshtml
@model KPI_Schedule.Models.Discipline

<table>
    <tr>
        <th>Name</th>
    </tr>
    <tr>
        <td>@Model.Name</td>
    </tr>
</table>
<a asp-action="List">Go Back</a>

Views/Discipline/Create.cshtml
@model KPI_Schedule.Models.Discipline

<form asp-action="Create">
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <input type="submit" value="Save" />
</form>
<a asp-action="List">Go Back</a>

Views/Discipline/Delete.cshtml
@model KPI_Schedule.Models.Discipline

<h4>Ви впевнені, що хочете видалити?</h4>

<table>
    <tr>
        <th>Name</th>
    </tr>
    <tr>
        <td>@Model.Name</td>
    </tr>
</table>
<form asp-action="Delete" asp-route-id="@Model.Id">
    <input type="submit" value="Delete" />
</form>
<a asp-action="List">Go Back</a>

Views/Discipline/Edit.cshtml
@model KPI_Schedule.Models.Discipline

<form asp-action="Edit">
    <input type="hidden" asp-for="Id" />
    <label asp-for="Name"></label>
    <input asp-for="Name" />
    <input type="submit" value="Save" />
</form>
<a asp-action="List">Go Back</a>

Views/Discipline/List.cshtml
@model IEnumerable<KPI_Schedule.Models.Discipline>

<a asp-action="Create" class="link-create">Create new item</a>
<table>
    <tr>
        <th>Name</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Name</td>
            <td>
                <a class="td-link" asp-controller="Discipline" asp-action="Choose" asp-route-id="@item.Id">Choose</a> |
                <a class="td-link" asp-controller="Discipline" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a class="td-link" asp-controller="Discipline" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
</table>